#! /bin/bash

case "$1" in
# Start the maestor console
	'console' )
		/opt/ros/fuerte/stacks/maestor/run/console.sh
	;;

# Start all channels and processes
	'sim-real' )
		/opt/ros/fuerte/stacks/maestor/run/sim-real.sh 
	;;

# Loads new home paramaters
	'sim' )
		/opt/ros/fuerte/stacks/maestor/run/sim.sh 
	;;

# Start hubo-read
	'real' )
		/opt/ros/fuerte/stacks/maestor/run/real.sh 
	;;

	*)
		echo
		echo 'console       : Starts the maestor console'
		echo 'sim-real      : Starts maestor with hubo-ach in sim-real mode'
		echo 'sim           : Starts maestor with hubo-ach in sim mode'
		echo 'real          : Starts maestor with hubo-ach in real mode'
		echo
		exit 1
	;;
esac

exit 0